# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_maker_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 509)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graph_maker_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 521, 461))
        self.frame.setStyleSheet("background-color: #4a536b;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.range_input = QtWidgets.QLineEdit(self.frame)
        self.range_input.setGeometry(QtCore.QRect(20, 180, 321, 51))
        font = QtGui.QFont()
        font.setFamily("v_ALoveOfThunder")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.range_input.setFont(font)
        self.range_input.setAutoFillBackground(False)
        self.range_input.setStyleSheet("background-color: #ff9a8d;\n"
"border: 2px solid  #aed6dc;\n"
"border-radius: 20px;")
        self.range_input.setFrame(True)
        self.range_input.setReadOnly(False)
        self.range_input.setClearButtonEnabled(False)
        self.range_input.setObjectName("range_input")
        self.func_input = QtWidgets.QLineEdit(self.frame)
        self.func_input.setGeometry(QtCore.QRect(20, 100, 321, 51))
        font = QtGui.QFont()
        font.setFamily("v_ALoveOfThunder")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.func_input.setFont(font)
        self.func_input.setStyleSheet("background-color: #ff9a8d;\n"
"border: 2px solid  #aed6dc;\n"
"border-radius: 20px;")
        self.func_input.setText("")
        self.func_input.setFrame(True)
        self.func_input.setReadOnly(False)
        self.func_input.setClearButtonEnabled(False)
        self.func_input.setObjectName("func_input")
        self.step_input = QtWidgets.QLineEdit(self.frame)
        self.step_input.setGeometry(QtCore.QRect(20, 260, 321, 51))
        font = QtGui.QFont()
        font.setFamily("v_ALoveOfThunder")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.step_input.setFont(font)
        self.step_input.setStyleSheet("background-color: #ff9a8d;\n"
"border: 2px solid  #aed6dc;\n"
"border-radius: 20px;")
        self.step_input.setText("")
        self.step_input.setFrame(True)
        self.step_input.setReadOnly(False)
        self.step_input.setClearButtonEnabled(False)
        self.step_input.setObjectName("step_input")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 321, 61))
        font = QtGui.QFont()
        font.setFamily("v_ALoveOfThunder")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #aed6dc")
        self.label.setObjectName("label")
        self.makegraph_btn = QtWidgets.QPushButton(self.frame)
        self.makegraph_btn.setGeometry(QtCore.QRect(130, 400, 231, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.makegraph_btn.setFont(font)
        self.makegraph_btn.setStyleSheet("color: #525252;\n"
"background-color:#aed6dc\n"
"")
        self.makegraph_btn.setObjectName("makegraph_btn")
        self.info_btn = QtWidgets.QPushButton(self.frame)
        self.info_btn.setGeometry(QtCore.QRect(470, 410, 41, 41))
        self.info_btn.setStyleSheet("background-color:#ff9a8d;\n"
"border-radius: 15px;\n"
"border: 2px solid #aed6dc;")
        self.info_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_btn.setIcon(icon1)
        self.info_btn.setIconSize(QtCore.QSize(40, 40))
        self.info_btn.setObjectName("info_btn")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(360, 100, 151, 221))
        self.scrollArea.setStyleSheet("background-color:#aed6dc;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 149, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.theme_btn = QtWidgets.QPushButton(self.frame)
        self.theme_btn.setGeometry(QtCore.QRect(10, 410, 41, 41))
        self.theme_btn.setStyleSheet("background-color:#ff9a8d;\n"
"border-radius: 15px;\n"
"border: 2px solid #aed6dc;")
        self.theme_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Light_Theme-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.theme_btn.setIcon(icon2)
        self.theme_btn.setIconSize(QtCore.QSize(35, 35))
        self.theme_btn.setObjectName("theme_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Graph Maker"))
        self.range_input.setPlaceholderText(_translate("MainWindow", "ВВЕДИТЕ ДИАПАЗОН ПОСТРОЕНИЯ"))
        self.func_input.setPlaceholderText(_translate("MainWindow", "ВВЕДИТЕ ФУНКЦИЮ"))
        self.step_input.setPlaceholderText(_translate("MainWindow", "ВВЕДИТЕ ШАГ"))
        self.label.setText(_translate("MainWindow", "GRAPH MAKER"))
        self.makegraph_btn.setText(_translate("MainWindow", "Построить график"))
